name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22" # Change this to your desired Go version

      - name: Install dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -coverprofile=coverage.out ./...

      - name: Convert coverage to Cobertura format
        run: gocover-cobertura < coverage.out > coverage.xml

      # - name: Upload coverage report
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: coverage-report
      #     path: coverage.xml
