name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22" # Change this to your desired Go version

      - name: Build
        run: go build -v ./...

      - name: Install gocover-cobertura
        run: go install github.com/boumenot/gocover-cobertura

      - name: Test
        run: |
          go test -coverprofile=coverage-hello.out ./...
          go test -coverprofile=coverage-mux.out -covermode=count github.com/gorilla/mux
          # Merge coverage profiles
          go tool cover -html=coverage-hello.out -o merged-hello.html
          go tool cover -html=coverage-mux.out -o merged-mux.html
          go tool cover -func=coverage-hello.out > merged-coverage.txt
          go tool cover -func=coverage-mux.out >> merged-coverage.txt

      - name: Convert merged coverage to Cobertura format
        run: gocover-cobertura < merged-coverage.txt > coverage.xml

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0

        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "30 80"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: always()
        with:
          recreate: true
          path: code-coverage-results.md
