name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22" # Change this to your desired Go version

      - name: Build
        run: go build -v ./...

      - name: Install gocover-cobertura
        run: go install github.com/boumenot/gocover-cobertura

      - name: Test
        run: |
          go test -coverprofile=coverage.out ./...
           go test -coverprofile=coverage-mux.out -covermode=count github.com/gorilla/mux

      - name: Convert coverage to Cobertura format
        run: gocover-cobertura < coverage.out > coverage.xml

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0

        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "20 80"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: always()
        with:
          recreate: true
          path: code-coverage-results.md
